# Generated by Django 3.2.14 on 2022-09-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asigm_1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
